- name: Playbook-git
  hosts: all
  tasks:
  - name: Install-git
    become: true
    yum: 
      name: git
      state: present
      update_cache: yes
    when: 
    - ansible_distribution == "RedHat"
    - ansible_pkg_mgr == "dnf"
